---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: geerlingguy/docker-centos7-ansible
    pre_build_image: true
lint: |
    set -e
    yamllint .
    ansible-lint .
provisioner:
  name: ansible
  ansible_args:
    - --skip-tags=no_testing
verifier:
  name: ansible
